### PR TITLE
Plugin add fails alternately

### PR DESCRIPTION
**Pull request by adonespitogo**
Here is my gulp task:

```
var gulp = require('gulp'),
    plugin = require('gulp-cordova-plugin'),
    plugins = require('../package.json').cordovaPlugins,
    del = require('del'),
    shell = require('shelljs');

gulp.task('plugins:empty', function () {
  return shell.rm('-r', 'plugins');
});

gulp.task('plugins', ['plugins:empty'], function() {

return gulp.src('plugins')
      .pipe(plugin(plugins));
});
```

For some reason, when I run this task, it fails. Then when I run again it succeeds. Then when I run again it fails the second time. When I run again, it succeeds the second time.

### CODE REVIEW

**Comment by adonespitogo** [comment]
And so this is how I solved it, using `shelljs`.

**Comment by SamVerschueren** [comment]
Hi @adonespitogo 

The gulp task you provided is not entirely correct. The directory you have to pass to the `.src()` function should be the directory of the entire project. Something like `.cordova` (default). And I would use `del` to remove the plugins out of the directory.

``` javascript
var gulp = require('gulp'),
    plugin = require('gulp-cordova-plugin'),
    pkg = require('../package.json'),
    del = require('del');

gulp.task('plugins:empty', function (done) {
    del('./cordova/plugins', done);
});

gulp.task('plugins', ['plugins:empty'], function() {
     return gulp.src('.cordova')
        .pipe(plugin(pkg.cordovaPlugins));
});
```

The reason why your code is not working is that plugins:empty is returning before the shell rm command is executed entirely. gulp expects a stream or a promise to be returned in the function or if nothing is returned, he expects the callback to be called. For more information, have a look at the [docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support) of gulp regarding async tasks.

Let me know if it's still not working, then I will have a deeper look into the solution.

**Comment by adonespitogo** [comment]
Hi @SamVerschueren 

Thanks for correcting, I'm very new to gulp and cordova. I've updated my gulp task but it's still not working.

``` js
var gulp = require('gulp'),
    plugin = require('gulp-cordova-plugin'),
    pkg = require('../package.json'),
    del = require('del'),
    path = require('path');


var cordovaLib = require('cordova-lib').cordova;
var projectRoot = cordovaLib.findProjectRoot();
var pluginsPath = path.join(projectRoot, 'plugins');

gulp.task('plugins:empty', function (done) {
    del(pluginsPath, done);
});

gulp.task('plugins', ['plugins:empty'], function() {
     return gulp.src(projectRoot)
        .pipe(plugin(pkg.cordovaPlugins));
});
```

Error log:

``` bash
adones@adones-S551LB:~/Projects/PNPAA-Ionic$ gulp plugins
[18:22:44] Using gulpfile ~/Projects/PNPAA-Ionic/gulpfile.js
[18:22:44] Starting 'plugins:empty'...
[18:22:44] Finished 'plugins:empty' after 48 ms
[18:22:44] Starting 'plugins'...
[18:22:44]  add cordova-plugin-device
[18:22:44]  add cordova-plugin-whitelist
[18:22:44]  add cordova-plugin-splashscreen
[18:22:44]  add com.ionic.keyboard
npm http GET http://registry.cordova.io/cordova-plugin-device
npm http GET http://registry.cordova.io/cordova-plugin-whitelist
npm http GET http://registry.cordova.io/cordova-plugin-splashscreen
npm http 404 http://registry.cordova.io/cordova-plugin-whitelist
[18:22:45] 'plugins' errored after 1.26 s
[18:22:45] Error in plugin 'gulp-cordova-plugin'
Message:
    404 Not Found: cordova-plugin-whitelist
npm http 404 http://registry.cordova.io/cordova-plugin-splashscreen
npm http 404 http://registry.cordova.io/cordova-plugin-device
adones@adones-S551LB:~/Projects/PNPAA-Ionic$
```

It still fails alternately.
By the way, when it fails, it was able to install one plugin - the last plugin in the `pkg.cordovaPlugins` array.

**Comment by SamVerschueren** [comment]
This is really odd. The message indicates, and I confirmed, that the plugin could not be found (hence the 404). If you navigate to http://registry.cordova.io/cordova-plugin-whitelist, it returns the message that the plugin could not be found. It doesn't alternate with me, sometimes it works, sometimes it doesn't. It looks like the cordova registry is having some issues. Because when it succeeds, it takes a long time to download the plugins.

If I test it with other plugins, it never fails...

``` javascript
gulp.task('plugins:empty', function (done) {
    del('.cordova/plugins', done);
});

gulp.task('plugins', ['plugins:empty'], function() {
     return gulp.src('.cordova')
        .pipe(plugin([
            'cordova-plugin-console',
            'cordova-plugin-globalization'
        ]));
});
```

**Comment by adonespitogo** [comment]
I see. It might be a cordova registry related issue and not the plugin
itself. Thanks so much for helping out. I will just use my own fork for the
mean time.

**Comment by SamVerschueren** [comment]
I will close this PR/discussion. I will create a new issue pointing to this PR to track the status on the cordova registry.

**Comment by adonespitogo** [comment]
Sure thanks.

**Comment by SamVerschueren** [comment]
Sorry, will reopen to make sure you don't remove your fork before this problem is resolved ;).

**Comment by adonespitogo** [comment]
Sure :+1:

**Comment by SamVerschueren** [comment]
Hi @adonespitogo. This should be fixed in `v1.2.0`. More information can be found here https://github.com/SamVerschueren/gulp-cordova-plugin/issues/6. Please reopen if this is not the case for you.

**Pull request closed without merging**
