### PR TITLE
allow passing fetch argument

### PR DESCRIPTION
**Pull request by airamrguez**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I might have missed a notification. So just wondering what this does or what use case it solves?

**Comment by airamrguez** [comment]
@SamVerschueren Some plugins in Cordova can use module dependencies. In order to install those dependencies you have to add a `fetch` parameter when you run `cordova plugin add`. [Here you can see an example](https://www.npmjs.com/package/cordova-plugin-localization-strings) of a plugin that needs to be installed using the fetch argument.

As you can see in the [Cordova source code](https://github.com/apache/cordova-lib/blob/fc32d62a262c90497ec83fe61e07b5717d8e81bf/cordova-lib/src/cordova/plugin.js#L133) `fetch` is false by default.

**Comment by SamVerschueren** [comment]
Seems legit! Can you document the option?

**Comment by airamrguez** [comment]
@SamVerschueren there you go!

**Comment by SamVerschueren** [comment]
Hi @airamrguez. Sorry for the late reply. I had to fix something else (#22) and decided to rewrite most of the plugin. Can you rebase to master? Tests will then pass as well. Sorry for the inconvenience!

**Review by SamVerschueren — APPROVED** [review]

**Comment by SamVerschueren** [comment]
Apparently never got a notification that you rebased on master. Merged it now! Thanks again 🎉

**Pull request merged**
